name:                ardener-server
version:             0.1.0.0
github:              "mic47/ardener-server"
license:             MIT
author:              "Michal N치n치si"
maintainer:          "michal.nanasi@gmail.com"
copyright:           "2018 Michal N치n치si"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mic47/ardener-server#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ardener-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ardener-server

tests:
  ardener-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ardener-server
